# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:year/:month/:day/:title/


# Setup
title:               Daniel.Y
tagline:             '专注搞一些事情'
description:         '记录一些学习，生活上的小事。'
url:                 'http://cai-yang.github.io'
baseurl:             ''
paginate:            5
gems: [jekyll-paginate]

# About/contact
author:
  name:              Daniel Yang
  url:               https://github.com/cai-yang
  email:             yc631207248@sjtu.edu.cn

# Custom vars
version:             1.0.0

# comments
duoshuo_shortname: daniely

# analytics
google_analytics_id: UA-94099121-1
